"""Add original filename to photo

Revision ID: 714da07ff39d
Revises: 75a0bf7dc8a4
Create Date: 2026-07-23 19:27:49.738621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714da07ff39d'
down_revision = '75a0bf7dc8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
