"""Add used in ShareCode

Revision ID: 7b5be81ea824
Revises: 1767726f827c
Create Date: 2026-07-24 12:29:51.183005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5be81ea824'
down_revision = '1767726f827c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_code', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
